### ISSUE TITLE
Publish new generator on npmjs

### ISSUE THREAD

**Issue by vlkz** [yeoman/generator-mobile#72]
Please switch to gulp and re-sync with the official WSK repo

**Comment by arthurvr** [comment]
We just didn't release the wsk version yet.

**Comment by crhym3** [comment]
The generator's using [gulp](https://github.com/yeoman/generator-mobile/blob/29c5dbcb947f219c82eca200514788218bf26603/app/index.js#L133). What are you guys talking about?

**Comment by arthurvr** [comment]
The guy is using generator-mobile, which in the past was using grunt. Now (since we switched over to wsk), it uses gulp. We just didn't release the version using WSK, so latest generator-mobile still uses grunt.

**Comment by crhym3** [comment]
Oh, you mean the npm package? No, we didn't. Although readme contains instructions on how to install this version from GitHub.

**Comment by arthurvr** [comment]
@crhym3 Could you close the issue?

**Comment by addyosmani** [comment]
Imo, we should just publish to npm. @crhym3 can you take care of that? I'm happy to add you to the package there if we haven't added you already.

**Comment by vlkz** [comment]
+1 to publish to npm.

That's where I got confused about what was going on. Awesome workflow tool, btw

**Comment by crhym3** [comment]
Hey Addy, I'll be happy to start publishing it to npm but yeah, I need to
be added to the package.

Thanks!

**Comment by crhym3** [comment]
Published as [2.0.0-alpha](https://www.npmjs.com/package/generator-mobile)

**Comment by addyosmani** [comment]
:+1:
