### ISSUE TITLE
[REQUEST] Reincorporate Framework Installation Option: Bootstrap, Foundation, etc.

### ISSUE THREAD

**Issue by vlkz** [yeoman/generator-mobile#73]
A lot of people will still be using these frameworks so it may be helpful to the majority to have it there as an option for now.

**Comment by crhym3** [comment]
The generator is now based on WSK. So, whatever WSK includes, it'll be in the generated app + 'gulp deploy'.

**Comment by vlkz** [comment]
Ah. Understood. Thanks!
