### ISSUE TITLE
yo mobile dies at gulpfile.js, writes empty ---------- file permissions

### ISSUE THREAD

**Issue by mashcode** [yeoman/generator-mobile#74]
fs.js:568
  function strWrapper(err, written) {
                ^
Error: EACCES, permission denied '/Users/marc/Sites/NYCompost/gulpfile.js'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at readFileAsString (/usr/local/lib/node_modules/generator-mobile/node_modules/yeoman-generator/lib/actions/wiring.js:277:13)
    at module.exports.yeoman.generators.Base.extend.writing.gulpfile (/usr/local/lib/node_modules/generator-mobile/app/index.js:137:27)
    at /usr/local/lib/node_modules/generator-mobile/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by crhym3** [comment]
For some reason it fails at [readFileAsString](https://github.com/yeoman/generator-mobile/blob/14dd99b4896ca5dc63fc7f9bee068048804f997f/app/index.js#L137)
@mashcode could you post the output of `ls -l /Users/marc/Sites/NYCompost`?

**Comment by mashcode** [comment]
I assume you want the output after 'yo mobile'?

Thanks

email marc@marcshifflett.com | mobile 917-570-7079

**Comment by crhym3** [comment]
Yes. Well, after that error happened.

**Comment by mashcode** [comment]
total 64

----------   1 marc  staff  11859 Feb 14 12:07 LICENSE

----------   1 marc  staff   5111 Feb 14 12:07 README.md

drwxr-xr-x  14 marc  staff    476 Feb 14 12:07 app

drwxr-xr-x   4 marc  staff    136 Feb 14 12:07 docs

----------   1 marc  staff   5625 Feb 14 12:07 gulpfile.js

----------   1 marc  staff    981 Feb 14 12:07 package.json
While it does scaffold, all files are empty

email marc@marcshifflett.com | mobile 917-570-7079

**Comment by crhym3** [comment]
Is it possible you have some weird sticky bit set on `/Users/marc/Sites/NYCompost` dir?
Can you try running it in a different directory, say `/Users/marc/tmp`, and if it still fails post the whole output of `yo mobile`? I'm unable to reproduce so far.

**Comment by mashcode** [comment]
Hey Alex, nope, nothing sticky. Tried installing in a clean dir. Also
checked node and node_modules permissions. Seems ok. Running the most
recent OS X Yosemite update, node v0.12.0, npm 2.5.1.

Thanks!

info Getting latest WSK release version ...

     info Found release v0.5.2

     info Fetching
https://github.com/google/web-starter-kit/archive/v0.5.2.zip ...

     info This might take a few moments

...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

✔ Done

     info Checking dependencies ...

✔ git

     info Configuring gulpfile.js

fs.js:568

  function strWrapper(err, written) {

                ^

Error: EACCES, permission denied
'/Users/marc/Sites/yomobile-test/gulpfile.js'

    at Error (native)

    at Object.fs.openSync (fs.js:502:18)

    at Object.fs.readFileSync (fs.js:354:15)

    at readFileAsString
(/usr/local/lib/node_modules/generator-mobile/node_modules/yeoman-generator/lib/actions/wiring.js:277:13)

    at module.exports.yeoman.generators.Base.extend.writing.gulpfile
(/usr/local/lib/node_modules/generator-mobile/app/index.js:137:27)

    at
/usr/local/lib/node_modules/generator-mobile/node_modules/yeoman-generator/lib/base.js:395:14

    at processImmediate [as _immediateCallback] (timers.js:358:17)

email marc@marcshifflett.com | mobile 917-570-7079

**Comment by crhym3** [comment]
Actually, I've just upgraded my npm version to 2.5.1 and started to have exact same issue on `npm test`.
Downgrading back to 1.4.28 doesn't help though :) 
Trying to figure this out...

**Comment by mashcode** [comment]
Comforting to know 🙏

**Comment by crhym3** [comment]
I filed https://github.com/kevva/download/issues/46

**Comment by mashcode** [comment]
Thanks Alex for the quick resolution! I guess I now have to learn the gulp way @_@
