### ISSUE TITLE
Environment config needed for tests should be defined in package.json

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-mobile#75]
In the `test` run script in package.json, not in .travis.yml.

https://github.com/yeoman/generator-mobile/commit/14dd99b4896ca5dc63fc7f9bee068048804f997f#commitcomment-9751194

**Comment by crhym3** [comment]
There is nothing to configure.
Like I was saying in the comment, the git-related tests are *not being run*, they are not failing.

There's more than just git configuration. A user might not even have git installed - I'm not going to ask them to install it or mess with their git configuration just to run those tests.

I believe `before_script` section of .travis.yml is where it belongs.

**Comment by sindresorhus** [comment]
What's the point of tests that only run sometimes?

**Comment by crhym3** [comment]
It's called CI. They always run on Travis.
