### ISSUE TITLE
Auto-install ruby deps

### ISSUE THREAD

**Issue by funkfinger** [yeoman/generator-mobile#78]
Should this generator have Gemfile since it requires the sass gem? On a fresh install I got this error:

    gulp-ruby-sass: stderr: /Users/jayw/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'sass' (>= 0) among 93 total gem(s) (Gem::LoadError)

Assuming Bundler & RVM, create `Gemfile`:

    ruby '2.2.0'
    source 'https://rubygems.org'

    group :development do
      gem 'sass', '~>3.4.0'
    end

and `.ruby-version`:

    2.2.0

and `.ruby-gemset`:

    generator-mobile

do a `bundle install` and all should be peachy.

**Comment by crhym3** [comment]
Not the generator itself but the Web Starter Kit - maybe yes. That's what this generator does - creates an app based on WSK. 

Or it could create this file from say app/templates/Gemfile.

**Comment by arthurvr** [comment]
Not worth it anymore. https://github.com/google/web-starter-kit/commit/5b860b2945376957663aa2f11b47b0c6a1387cdb

**Comment by arthurvr** [comment]
The latest version of wsk does not use ruby sass anymore.

**Comment by crhym3** [comment]
v0.5.2 still shows up as the latest in https://api.github.com/repos/google/web-starter-kit/releases

**Comment by arthurvr** [comment]
> v0.5.2 still shows up as the latest in https://api.github.com/repos/google/web-starter-kit/releases

@crhym3 v0.5.3 was [tagged January 23](https://github.com/google/web-starter-kit/tags).

Can somebody close this issue?

**Comment by crhym3** [comment]
it was a quiet release, it won't show up.

**Comment by addyosmani** [comment]
I've fixed it so that 0.5.3 should now appear in the correct releases returned by the API. If there are still issues feel free to reopen and I'll address.
