### ISSUE TITLE
contributions reverted, why?

### ISSUE THREAD

**Issue by corburnos** [yeoman/generator-mobile#82]
In the past I contributed to this repo. I liked it and you was really quick to merge things. Thanks therefore. Though I recently logged into github again and it seems like I lose everything. I understand that the change was reverted but I'd like to know why? I can still find my PR in the list as "merged" but it isn't on the log nor the github contributions table anymore. Why?

**Comment by arthurvr** [comment]
I don't remember the PR anymore, but I guess we didn't revert it. A while ago we just got rid of all git history on this repo as @crhym3 rewrote the generator to scaffold WSK.

FYI everything still is in the [`legancy`](https://github.com/yeoman/generator-mobile/tree/legacy) branch.

**Comment by corburnos** [comment]
Thank you. I'd suggest to just add things instead of force pushing and changing history! read about force pushing on the git site :-1: @crhym3 !!!

**Comment by corburnos** [comment]
:-1:

**Comment by corburnos** [comment]
:-1:

**Comment by corburnos** [comment]
:-1:
